In [26]:
from tensorflow.keras.preprocessing.text import one_hot

In [27]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [28]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [29]:
## Define the Vocabulary size.
voc_size=10000

In [30]:
## One Hot Representation
one_hot_rep=[one_hot(words,voc_size) for words in sent]
one_hot_rep


[[4542, 6951, 9793, 7454],
 [4542, 6951, 9793, 4032],
 [4542, 7146, 9793, 1902],
 [1932, 4354, 5975, 6018, 9256],
 [1932, 4354, 5975, 6018, 1884],
 [225, 4542, 387, 9793, 5274],
 [9703, 8544, 3099, 6018]]

In [31]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [33]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4542 6951 9793 7454]
 [   0    0    0    0 4542 6951 9793 4032]
 [   0    0    0    0 4542 7146 9793 1902]
 [   0    0    0 1932 4354 5975 6018 9256]
 [   0    0    0 1932 4354 5975 6018 1884]
 [   0    0    0  225 4542  387 9793 5274]
 [   0    0    0    0 9703 8544 3099 6018]]


In [34]:
## Feature Representation
dim=10

In [42]:
model=Sequential()
#model.add(Embedding(voc_size,dim,input_length=sent_length))
model.add(Embedding(voc_size ,dim,input_shape=(sent_length,)))
#model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

e:\KRISH-NAIK\GEN-AI-WITH-LC-AND-HF\E-T-E-PROJ-IMP-USI-RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [43]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01014867,  0.03439099,  0.00546186,  0.00861728,
         -0.012208  ,  0.01105436,  0.02447318,  0.02996219,
          0.02561878,  0.00761818],
        [-0.00190022, -0.01947881,  0.04848469, -0.04524818,
          0.03936919, -0.01573233,  0.00051643,  0.00956323,
         -0.02675479,  0.00647078],
        [-0.04462017,  0.02752319,  0.03438047, -0.0

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 4542, 6951, 9793, 7454], dtype=int32)

In [47]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


array([[[ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01015114,  0.03811813,  0.03708028, -0.03255337,
         -0.04396264, -0.0457867 ,  0.01585087,  0.0156183 ,
         -0.02855455,  0.02748296],
        [ 0.01014867,  0.03439099,  0.00546186,  0.00861728,
         -0.012208  ,  0.01105436,  0.02447318,  0.02996219,
          0.02561878,  0.00761818],
        [-0.00190022, -0.01947881,  0.04848469, -0.04524818,
          0.03936919, -0.01573233,  0.00051643,  0.00956323,
         -0.02675479,  0.00647078],
        [-0.04462017,  0.02752319,  0.03438047, -0.0